export const playerFields = [
    { field: 'name', title: 'Имя' },
    { field: 'full_name', title: 'Полное имя' },
    { field: 'birth_date', title: 'Дата рождения' },
    { field: 'age', title: 'Возраст' },
    { field: 'height_cm', title: 'Рост (см)' },
    { field: 'weight_kgs', title: 'Вес (кг)' },
    { field: 'positions', title: 'Позиции' },
    { field: 'nationality', title: 'Национальность' },
    { field: 'overall_rating', title: 'Общий рейтинг' },
    { field: 'potential', title: 'Потенциал' },
    { field: 'value_euro', title: 'Стоимость (евро)', needtoFormat: true },
    { field: 'wage_euro', title: 'Зарплата (евро)', needtoFormat: true },
    { field: 'preferred_foot', title: 'Предпочитаемая нога' },
    { field: 'international_reputation', title: 'Международная репутация' },
    { field: 'weak_foot', title: 'Слабая нога' },
    { field: 'skill_moves', title: 'Навыки' },
    { field: 'body_type', title: 'Тип телосложения' },
    { field: 'release_clause_euro', title: 'Клаусула (евро)' },
    { field: 'national_team', title: 'Сборная команда' },
    { field: 'national_rating', title: 'Рейтинг в сборной' },
    { field: 'national_team_position', title: 'Позиция в сборной' },
    { field: 'national_jersey_number', title: 'Номер в сборной' },
    { field: 'crossing', title: 'Навесы' },
    { field: 'finishing', title: 'Завершение' },
    { field: 'heading_accuracy', title: 'Точность удара головой' },
    { field: 'short_passing', title: 'Короткий пас' },
    { field: 'volleys', title: 'Воллей' },
    { field: 'dribbling', title: 'Дриблинг' },
    { field: 'curve', title: 'Эффект' },
    { field: 'freekick_accuracy', title: 'Точность штрафных' },
    { field: 'long_passing', title: 'Длинный пас' },
    { field: 'ball_control', title: 'Контроль мяча' },
    { field: 'acceleration', title: 'Ускорение' },
    { field: 'sprint_speed', title: 'Скорость спринта' },
    { field: 'agility', title: 'Ловкость' },
    { field: 'reactions', title: 'Реакции' },
    { field: 'balance', title: 'Баланс' },
    { field: 'shot_power', title: 'Сила удара' },
    { field: 'jumping', title: 'Прыжки' },
    { field: 'stamina', title: 'Выносливость' },
    { field: 'strength', title: 'Сила' },
    { field: 'long_shots', title: 'Дальние удары' },
    { field: 'aggression', title: 'Агрессия' },
    { field: 'interceptions', title: 'Перехваты' },
    { field: 'positioning', title: 'Позиционирование' },
    { field: 'vision', title: 'Видение поля' },
    { field: 'penalties', title: 'Пенальти' },
    { field: 'composure', title: 'Хладнокровие' },
    { field: 'marking', title: 'Опека' },
    { field: 'standing_tackle', title: 'Отбор мяча' },
    { field: 'sliding_tackle', title: 'Подкат' }
]

export const playerCompareFields = [
    { field: 'name', title: 'Имя' },
    { field: 'overall_rating', title: 'Общий рейтинг' },
    { field: 'potential', title: 'Потенциал' },
    { field: 'value_euro', title: 'Стоимость (евро)', needtoFormat: true },
    { field: 'weak_foot', title: 'Слабая нога' },
    { field: 'skill_moves', title: 'Навыки' },
    { field: 'national_rating', title: 'Рейтинг в сборной' },
    { field: 'crossing', title: 'Навесы' },
    { field: 'finishing', title: 'Завершение' },
    { field: 'heading_accuracy', title: 'Точность удара головой' },
    { field: 'short_passing', title: 'Короткий пас' },
    { field: 'volleys', title: 'Воллей' },
    { field: 'dribbling', title: 'Дриблинг' },
    { field: 'curve', title: 'Эффект' },
    { field: 'freekick_accuracy', title: 'Точность штрафных' },
    { field: 'long_passing', title: 'Длинный пас' },
    { field: 'ball_control', title: 'Контроль мяча' },
    { field: 'acceleration', title: 'Ускорение' },
    { field: 'sprint_speed', title: 'Скорость спринта' },
    { field: 'agility', title: 'Ловкость' },
    { field: 'reactions', title: 'Реакции' },
    { field: 'balance', title: 'Баланс' },
    { field: 'shot_power', title: 'Сила удара' },
    { field: 'jumping', title: 'Прыжки' },
    { field: 'stamina', title: 'Выносливость' },
    { field: 'strength', title: 'Сила' },
    { field: 'long_shots', title: 'Дальние удары' },
    { field: 'aggression', title: 'Агрессия' },
    { field: 'interceptions', title: 'Перехваты' },
    { field: 'positioning', title: 'Позиционирование' },
    { field: 'vision', title: 'Видение поля' },
    { field: 'penalties', title: 'Пенальти' },
    { field: 'composure', title: 'Хладнокровие' },
    { field: 'marking', title: 'Опека' },
    { field: 'standing_tackle', title: 'Отбор мяча' },
    { field: 'sliding_tackle', title: 'Подкат' }
]
